-- Идемпотентно для повторного запуска (одна БД для нескольких сервисов / пересоздание контейнеров).
CREATE TABLE IF NOT EXISTS trade_selection (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    steam_id    VARCHAR(32) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_trade_selection_steam_id UNIQUE (steam_id)
);

CREATE TABLE IF NOT EXISTS trade_selection_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_selection_id  BIGINT NOT NULL,
    asset_id            VARCHAR(64) NOT NULL,
    class_id            VARCHAR(64) NOT NULL,
    sort_order          INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_trade_selection_item_selection FOREIGN KEY (trade_selection_id) REFERENCES trade_selection (id) ON DELETE CASCADE,
    CONSTRAINT uq_trade_selection_item_asset UNIQUE (trade_selection_id, asset_id)
);

CREATE INDEX IF NOT EXISTS ix_trade_selection_steam_id ON trade_selection (steam_id);
CREATE INDEX IF NOT EXISTS ix_trade_selection_item_selection_id ON trade_selection_item (trade_selection_id);
